var __fbResArrayEN =
{
	'formbuilder': 'Form Builder!',
	'version': 'Ver 0.1',
	'file': 'Files',
	'operation': 'Operation',
	'font': 'FONT',
	'paragraph': 'Paragraph',
	'sheet': 'Sheet',
	'drinkcupcoffee': 'Drink a cup of Coffee,',
	"waitmoment": "wait a moment！",
	"setting": "Setting:",
	"conditionhiding": "condition of hiding:",
	"hidden": "Hidden:",
	"allowmuplitvalue": "Allow Muplit Value:",
	"characterlength": "Character length:",
	"creatcalculation": "creatcalculation",
	"viewcalculation": "viewcalculation",
	"calculation": "calculation",
	"editable": "editable",
	"codetype": "codetype:",
	"richtext": "richtext",
	"combo": "combo",
	"radio": "radio",
	"checkbox": "checkbox",
	"dialogue": "dialogue",
	"number": "number",
	"date": "date",
	"text": "text",
	"edittype": "edittype:",
	"code": "code:",
	"editable": "editable",
	"list": "list",
	"url": "url",
	"sql": "sql",
	'datasourcetype': 'data source type:',
	'datasourcetsetting': 'data sourcet setting:',
	'maxrows': 'maxrows:',
	'content': 'content:',
	'paging': 'Paging:',
	'datasourcetsetting': 'data sourcet setting:',
	'allowmuplit': 'Allow Muplit:',
	'option': 'option'
};

var __fbResArrayCN =
{
	'formbuilder': '表单设计器 | 中国程序员大联盟',
	'version': 'Ver 0.1',
	'file': '文件',
	'operation': '操作',
	'font': '字体',
	'paragraph': 'Paragraph',
	'sheet': '工作簿',
	'drinkcupcoffee': '喝杯咖啡,',
	"waitmoment": "稍等！",
	"setting": "设置:",
	"rowid":"唯一标识:",
	"conditionhiding": "隐藏条件:",
	"hidden": "隐藏:",
	"allowmuplitvalue": "运行多值:",
	"characterlength": "字符长度:",
	"creatcalculation": "创建时计算",
	"viewcalculation": "显示计算",
	"calculation": "实时计算",
	"codetype": "类型:",
	"richtext": "富文本",
	"combo": "下拉",
	"linklist":"上级联动",
	"radio": "单选按钮",
	"checkbox": "多选按钮",
	"dialogue": "对话框",
	"number": "数值",
	"date": "日期",
	"text": "文本",
	"image": "图片",
	"button":"按钮",
	"edittype": "编辑类型:",
	"placeholder": '占位符:',
	"displayname":"显示名称:",
	"code": "名称:",
	"editable": "可编辑",
	"list": "列表",
	"url": "链接",
	"sql": "SQL语句",
	'datasourcetype': '数据来源类型:',
	'datasourcetsetting': '数据来源设置:',
	'maxrows': '最大行数:',
	'content': '内容:',
	'paging': '分页:',
	'allowmuplit': '运行多值:',
	'option': '选项:',
	'New':'新建',
	'Ok':'确定',
	'Cancel':'取消',
	'data property':'表格属性',
	'nunctincidunt':'域信息',
	'proindolor':'控件',
	'Target':'目标',
	'ExecuteCode':'执行代码',
	'URL':'目标地址',
	'savefile':'保存文件:',
	'openfile':'打开文件:',
	'verify':'校验选项'
};
	