USE [OTMS]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[fn_pub_basic_GetPinYin]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[fn_pub_basic_GetPinYin]
GO

USE [OTMS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[fn_pub_basic_GetPinYin]
(
	@Str NVARCHAR(100),
	@Abbr TINYINT,
	@SkipRegion TINYINT
)
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @Re NVARCHAR(MAX), @Crs NVARCHAR(10);
	DECLARE @StrLen INT;
	DECLARE @tRe NVARCHAR(20);
	SELECT @StrLen = LEN(@Str), @Re = '', @tRe = '';
	DECLARE @StrAbbr NVARCHAR(2048);
	SET @StrAbbr = N'';
	
	WHILE @StrLen > 0
	BEGIN	
		SET @Crs = SUBSTRING(@Str, @StrLen, 1);
		SET @tRe= (CASE
		WHEN @SkipRegion = 1 AND @Crs = N'Ê¡' THEN '' 
		WHEN @SkipRegion = 1 AND @Crs = N'ÊÐ' THEN '' 
		WHEN @SkipRegion = 1 AND @Crs = N'Çø' THEN '' 
		WHEN @SkipRegion = 1 AND @Crs = N'ÏØ' THEN '' 
        WHEN @Crs<'ß¹' THEN @Crs 
        WHEN @Crs<='…' THEN 'A'
        WHEN @Crs<='ìa' THEN 'Ai'
        WHEN @Crs<='÷ö' THEN 'An'
        WHEN @Crs<='ál' THEN 'Ang'
        WHEN @Crs<='òˆ' THEN 'Ao'
        WHEN @Crs<='™ñ' THEN 'Ba'
        WHEN @Crs<='®B' THEN 'Bai'
        WHEN @Crs<='°ê' THEN 'Ban'
        WHEN @Crs<='æ^' THEN 'Bang'
        WHEN @Crs<='èt' THEN 'Bao'
        WHEN @Crs<='öÍ' THEN 'Bei'
        WHEN @Crs<='Ý™' THEN 'Ben'
        WHEN @Crs<='ça' THEN 'Beng'
        WHEN @Crs<='ü„' THEN 'Bi'
        WHEN @Crs<='×ƒ' THEN 'Bian'
        WHEN @Crs<='÷B' THEN 'Biao'
        WHEN @Crs<='•' THEN 'Bie'
        WHEN @Crs<='ôW' THEN 'Bin'
        WHEN @Crs<='ìh' THEN 'Bing'
        WHEN @Crs<='ÊN' THEN 'Bo'
        WHEN @Crs<='²¾' THEN 'Bu'
        WHEN @Crs<='‡Í' THEN 'Ca'
        WHEN @Crs<='k' THEN 'Cai'
        WHEN @Crs<=' |' THEN 'Can'
        WHEN @Crs<='Ù‰' THEN 'Cang'
        WHEN @Crs<='ü' THEN 'Cao'
        WHEN @Crs<='ºu' THEN 'Ce'
        WHEN @Crs<='¸’' THEN 'Cen'
        WHEN @Crs<='u' THEN 'Ceng'
        WHEN @Crs<='ÔŒ' THEN 'Cha'
        WHEN @Crs<='‡Ð' THEN 'Chai'
        WHEN @Crs<='î' THEN 'Chan'
        WHEN @Crs<='ío' THEN 'Chang'
        WHEN @Crs<='Óe' THEN 'Chao'
        WHEN @Crs<=' …' THEN 'Che'
        WHEN @Crs<='×' THEN 'Chen'
        WHEN @Crs<='³Ó' THEN 'Cheng'
        WHEN @Crs<='úu' THEN 'Chi'
        WHEN @Crs<='ã|' THEN 'Chong'
        WHEN @Crs<='šŽ' THEN 'Chou'
        WHEN @Crs<='´£' THEN 'Chu'
        WHEN @Crs<='õß' THEN 'Chuai'
        WHEN @Crs<='úE' THEN 'Chuan'
        WHEN @Crs<='í' THEN 'Chuang'
        WHEN @Crs<='îq' THEN 'Chui'
        WHEN @Crs<='´À' THEN 'Chun'
        WHEN @Crs<='¿W' THEN 'Chuo'
        WHEN @Crs<='†ï' THEN 'Ci'
        WHEN @Crs<='Ö' THEN 'Cong'
        WHEN @Crs<='Ý' THEN 'Cou'
        WHEN @Crs<='î•' THEN 'Cu'
        WHEN @Crs<='ìà' THEN 'Cuan'
        WHEN @Crs<='Ä›' THEN 'Cui'
        WHEN @Crs<='»v' THEN 'Cun'
        WHEN @Crs<='åe' THEN 'Cuo'
        WHEN @Crs<='™\' THEN 'Da'
        WHEN @Crs<='ì^' THEN 'Dai'
        WHEN @Crs<='ð…' THEN 'Dan'
        WHEN @Crs<='êW' THEN 'Dang'
        WHEN @Crs<='ôî' THEN 'Dao'
        WHEN @Crs<='µÄ' THEN 'De'
        WHEN @Crs<='’Y' THEN 'Den'
        WHEN @Crs<='ç‹' THEN 'Deng'
        WHEN @Crs<='ÏE' THEN 'Di'
        WHEN @Crs<='àÇ' THEN 'Dia'
        WHEN @Crs<='ò›' THEN 'Dian'
        WHEN @Crs<='èS' THEN 'Diao'
        WHEN @Crs<='‡Ã' THEN 'Die'
        WHEN @Crs<='îr' THEN 'Ding'
        WHEN @Crs<='äA' THEN 'Diu'
        WHEN @Crs<='ëš' THEN 'Dong'
        WHEN @Crs<='ôa' THEN 'Dou'
        WHEN @Crs<='ó¼' THEN 'Du'
        WHEN @Crs<='…¶' THEN 'Duan'
        WHEN @Crs<='×m' THEN 'Dui'
        WHEN @Crs<='Ûv' THEN 'Dun'
        WHEN @Crs<='ùz' THEN 'Duo'
        WHEN @Crs<='÷{' THEN 'E'
        WHEN @Crs<='Þô' THEN 'En'
        WHEN @Crs<='íE' THEN 'Eng'
        WHEN @Crs<='˜Þ' THEN 'Er'
        WHEN @Crs<='óŒ' THEN 'Fa'
        WHEN @Crs<='ž~' THEN 'Fan'
        WHEN @Crs<='·Å' THEN 'Fang'
        WHEN @Crs<='ì]' THEN 'Fei'
        WHEN @Crs<='÷a' THEN 'Fen'
        WHEN @Crs<='Ò…' THEN 'Feng'
        WHEN @Crs<='—‚' THEN 'Fo'
        WHEN @Crs<='ø]' THEN 'Fou'
        WHEN @Crs<='ªg' THEN 'Fu'
        WHEN @Crs<='ôp' THEN 'Ga'
        WHEN @Crs<='­y' THEN 'Gai'
        WHEN @Crs<='ž¸' THEN 'Gan'
        WHEN @Crs<='‘ß' THEN 'Gang'
        WHEN @Crs<='ä†' THEN 'Gao'
        WHEN @Crs<='ª˜' THEN 'Ge'
        WHEN @Crs<='½o' THEN 'Gei'
        WHEN @Crs<='“j' THEN 'Gen'
        WHEN @Crs<='ˆí' THEN 'Geng'
        WHEN @Crs<='ƒÅ' THEN 'Gong'
        WHEN @Crs<='Ù' THEN 'Gou'
        WHEN @Crs<='î™' THEN 'Gu'
        WHEN @Crs<='ÔŸ' THEN 'Gua'
        WHEN @Crs<='s' THEN 'Guai'
        WHEN @Crs<='÷}' THEN 'Guan'
        WHEN @Crs<='“Ñ' THEN 'Guang'
        WHEN @Crs<='÷i' THEN 'Gui'
        WHEN @Crs<='Ö' THEN 'Gun'
        WHEN @Crs<='ÄB' THEN 'Guo'
        WHEN @Crs<='¹þ' THEN 'Ha'
        WHEN @Crs<='ðŽ' THEN 'Hai'
        WHEN @Crs<='ú[' THEN 'Han'
        WHEN @Crs<='ãì' THEN 'Hang'
        WHEN @Crs<='ƒÁ' THEN 'Hao'
        WHEN @Crs<='ìg' THEN 'He'
        WHEN @Crs<='‹Ï' THEN 'Hei'
        WHEN @Crs<='ºÞ' THEN 'Hen'
        WHEN @Crs<='ˆý' THEN 'Heng'
        WHEN @Crs<='ô\' THEN 'Hong'
        WHEN @Crs<='÷c' THEN 'Hou'
        WHEN @Crs<='ûI' THEN 'Hu'
        WHEN @Crs<='Ìs' THEN 'Hua'
        WHEN @Crs<='Ì|' THEN 'Huai'
        WHEN @Crs<='öd' THEN 'Huan'
        WHEN @Crs<='æw' THEN 'Huang'
        WHEN @Crs<='îœ' THEN 'Hui'
        WHEN @Crs<='ÕŸ' THEN 'Hun'
        WHEN @Crs<='‰þ' THEN 'Huo'
        WHEN @Crs<='óK' THEN 'Ji'
        WHEN @Crs<='†í' THEN 'Jia'
        WHEN @Crs<='èƒ' THEN 'Jian'
        WHEN @Crs<='Ö˜' THEN 'Jiang'
        WHEN @Crs<='á†' THEN 'Jiao'
        WHEN @Crs<='ÀT' THEN 'Jie'
        WHEN @Crs<='ý„' THEN 'Jin'
        WHEN @Crs<='¸„' THEN 'Jing'
        WHEN @Crs<='ÌW' THEN 'Jiong'
        WHEN @Crs<='™ã' THEN 'Jiu'
        WHEN @Crs<=' „' THEN 'Ju'
        WHEN @Crs<='Á\' THEN 'Juan'
        WHEN @Crs<='è‘' THEN 'Jue'
        WHEN @Crs<='”h' THEN 'Jun'
        WHEN @Crs<='ãl' THEN 'Ka'
        WHEN @Crs<='f' THEN 'Kai'
        WHEN @Crs<='²™' THEN 'Kan'
        WHEN @Crs<='é`' THEN 'Kang'
        WHEN @Crs<='õ‘' THEN 'Kao'
        WHEN @Crs<='òS' THEN 'Ke'
        WHEN @Crs<='Ñy' THEN 'Ken'
        WHEN @Crs<='çH' THEN 'Keng'
        WHEN @Crs<='W' THEN 'Kong'
        WHEN @Crs<='úd' THEN 'Kou'
        WHEN @Crs<='‡¿' THEN 'Ku'
        WHEN @Crs<='óg' THEN 'Kua'
        WHEN @Crs<='÷d' THEN 'Kuai'
        WHEN @Crs<='¸U' THEN 'Kuan'
        WHEN @Crs<='èk' THEN 'Kuang'
        WHEN @Crs<='è^' THEN 'Kui'
        WHEN @Crs<='±—' THEN 'Kun'
        WHEN @Crs<='·i' THEN 'Kuo'
        WHEN @Crs<='íB' THEN 'La'
        WHEN @Crs<='»[' THEN 'Lai'
        WHEN @Crs<='¼h' THEN 'Lan'
        WHEN @Crs<='†}' THEN 'Lang'
        WHEN @Crs<='Ü~' THEN 'Lao'
        WHEN @Crs<='ðE' THEN 'Le'
        WHEN @Crs<='Ãš' THEN 'Lei'
        WHEN @Crs<='±œ' THEN 'Leng'
        WHEN @Crs<='­€' THEN 'Li'
        WHEN @Crs<='‚z' THEN 'Lia'
        WHEN @Crs<='À~' THEN 'Lian'
        WHEN @Crs<='åy' THEN 'Liang'
        WHEN @Crs<='²t' THEN 'Liao'
        WHEN @Crs<='÷v' THEN 'Lie'
        WHEN @Crs<='Þ`' THEN 'Lin'
        WHEN @Crs<='žâ' THEN 'Ling'
        WHEN @Crs<='¿©' THEN 'Liu'
        WHEN @Crs<='ÚL' THEN 'Long'
        WHEN @Crs<='çU' THEN 'Lou'
        WHEN @Crs<='ëª' THEN 'Lu'
        WHEN @Crs<='èr' THEN 'Lv'
        WHEN @Crs<='y' THEN 'Luan'
        WHEN @Crs<='”^' THEN 'Lue'
        WHEN @Crs<='Õ“' THEN 'Lun'
        WHEN @Crs<='÷w' THEN 'Luo'
        WHEN @Crs<='Âï' THEN 'Ma'
        WHEN @Crs<='ìA' THEN 'Mai'
        WHEN @Crs<='Ìp' THEN 'Man'
        WHEN @Crs<='Ï‘' THEN 'Mang'
        WHEN @Crs<='†x' THEN 'Mao'
        WHEN @Crs<='°Z' THEN 'Me'
        WHEN @Crs<='‡ª' THEN 'Mei'
        WHEN @Crs<='‚ƒ' THEN 'Men'
        WHEN @Crs<='ìD' THEN 'Meng'
        WHEN @Crs<='Á]' THEN 'Mi'
        WHEN @Crs<='üI' THEN 'Mian'
        WHEN @Crs<='R' THEN 'Miao'
        WHEN @Crs<='÷x' THEN 'Mie'
        WHEN @Crs<='öš' THEN 'Min'
        WHEN @Crs<='Ôš' THEN 'Ming'
        WHEN @Crs<='Ö‡' THEN 'Miu'
        WHEN @Crs<='ñò' THEN 'Mo'
        WHEN @Crs<='üE' THEN 'Mou'
        WHEN @Crs<='”æ' THEN 'Mu'
        WHEN @Crs<='ô›' THEN 'Na'
        WHEN @Crs<='år' THEN 'Nai'
        WHEN @Crs<='‹R' THEN 'Nan'
        WHEN @Crs<='ýQ' THEN 'Nang'
        WHEN @Crs<='Äž' THEN 'Nao'
        WHEN @Crs<='ÄØ' THEN 'Ne'
        WHEN @Crs<='Ÿˆ' THEN 'Nei'
        WHEN @Crs<='ÄÛ' THEN 'Nen'
        WHEN @Crs<='ÄÜ' THEN 'Neng'
        WHEN @Crs<='‹ò' THEN 'Ni'
        WHEN @Crs<='Åˆ' THEN 'Nian'
        WHEN @Crs<='á„' THEN 'Niang'
        WHEN @Crs<='ëå' THEN 'Niao'
        WHEN @Crs<='è' THEN 'Nie'
        WHEN @Crs<='’Œ' THEN 'Nin'
        WHEN @Crs<='ô' THEN 'Ning'
        WHEN @Crs<='ì' THEN 'Niu'
        WHEN @Crs<='ýP' THEN 'Nong'
        WHEN @Crs<='×k' THEN 'Nou'
        WHEN @Crs<='“x' THEN 'Nu'
        WHEN @Crs<='ô¬' THEN 'Nv'
        WHEN @Crs<='¯‘' THEN 'Nue'
        WHEN @Crs<=' \' THEN 'Nuan'
        WHEN @Crs<='–þ' THEN 'Nuo'
        WHEN @Crs<='íM' THEN 'O'
        WHEN @Crs<='a' THEN 'Ou'
        WHEN @Crs<='Ð’' THEN 'Pa'
        WHEN @Crs<='´s' THEN 'Pai'
        WHEN @Crs<='è‹' THEN 'Pan'
        WHEN @Crs<='ÅÖ' THEN 'Pang'
        WHEN @Crs<='µ^' THEN 'Pao'
        WHEN @Crs<='Þ\' THEN 'Pei'
        WHEN @Crs<='†Ï' THEN 'Pen'
        WHEN @Crs<='†Ô' THEN 'Peng'
        WHEN @Crs<='ûG' THEN 'Pi'
        WHEN @Crs<='ò_' THEN 'Pian'
        WHEN @Crs<='‘G' THEN 'Piao'
        WHEN @Crs<='‹±' THEN 'Pie'
        WHEN @Crs<='Æ¸' THEN 'Pin'
        WHEN @Crs<='ÌO' THEN 'Ping'
        WHEN @Crs<='ÆÇ' THEN 'Po'
        WHEN @Crs<='†R' THEN 'Pou'
        WHEN @Crs<='ÆØ' THEN 'Pu'
        WHEN @Crs<='Ï„' THEN 'Qi'
        WHEN @Crs<='÷Ä' THEN 'Qia'
        WHEN @Crs<='¿y' THEN 'Qian'
        WHEN @Crs<='­™' THEN 'Qiang'
        WHEN @Crs<='ÜN' THEN 'Qiao'
        WHEN @Crs<='»]' THEN 'Qie'
        WHEN @Crs<='ÌC' THEN 'Qin'
        WHEN @Crs<='™¼' THEN 'Qing'
        WHEN @Crs<='­Ž' THEN 'Qiong'
        WHEN @Crs<='ôÜ' THEN 'Qiu'
        WHEN @Crs<='ÓY' THEN 'Qu'
        WHEN @Crs<='„ñ' THEN 'Quan'
        WHEN @Crs<='µ]' THEN 'Que'
        WHEN @Crs<='‡Ý' THEN 'Qun'
        WHEN @Crs<='™L' THEN 'Ran'
        WHEN @Crs<='×Œ' THEN 'Rang'
        WHEN @Crs<='À@' THEN 'Rao'
        WHEN @Crs<='Ÿá' THEN 'Re'
        WHEN @Crs<='ïš' THEN 'Ren'
        WHEN @Crs<='ê—' THEN 'Reng'
        WHEN @Crs<='ñ_' THEN 'Ri'
        WHEN @Crs<='·\' THEN 'Rong'
        WHEN @Crs<='Ž]' THEN 'Rou'
        WHEN @Crs<='”J' THEN 'Ru'
        WHEN @Crs<='µO' THEN 'Ruan'
        WHEN @Crs<='‰Ç' THEN 'Rui'
        WHEN @Crs<='˜ô' THEN 'Run'
        WHEN @Crs<='úU' THEN 'Ruo'
        WHEN @Crs<='–Ó' THEN 'Sa'
        WHEN @Crs<='Ìƒ' THEN 'Sai'
        WHEN @Crs<='éd' THEN 'San'
        WHEN @Crs<='†Ê' THEN 'Sang'
        WHEN @Crs<='ó' THEN 'Sao'
        WHEN @Crs<='ïo' THEN 'Se'
        WHEN @Crs<='ºd' THEN 'Sen'
        WHEN @Crs<='¿L' THEN 'Seng'
        WHEN @Crs<='ö®' THEN 'Sha'
        WHEN @Crs<='•ñ' THEN 'Shai'
        WHEN @Crs<='÷X' THEN 'Shan'
        WHEN @Crs<='¾y' THEN 'Shang'
        WHEN @Crs<='äû' THEN 'Shao'
        WHEN @Crs<='™Ý' THEN 'She'
        WHEN @Crs<='¯”' THEN 'Shen'
        WHEN @Crs<='Ù‹' THEN 'Sheng'
        WHEN @Crs<='­—' THEN 'Shi'
        WHEN @Crs<='æ' THEN 'Shou'
        WHEN @Crs<='Ì ' THEN 'Shu'
        WHEN @Crs<='ÕX' THEN 'Shua'
        WHEN @Crs<='…i' THEN 'Shuai'
        WHEN @Crs<='ÄY' THEN 'Shuan'
        WHEN @Crs<='ž“' THEN 'Shuang'
        WHEN @Crs<='Ë¯' THEN 'Shui'
        WHEN @Crs<='ôB' THEN 'Shun'
        WHEN @Crs<='èp' THEN 'Shuo'
        WHEN @Crs<='r' THEN 'Si'
        WHEN @Crs<='æ' THEN 'Song'
        WHEN @Crs<='¯˜' THEN 'Sou'
        WHEN @Crs<='ú‰' THEN 'Su'
        WHEN @Crs<='Ëã' THEN 'Suan'
        WHEN @Crs<='ç›' THEN 'Sui'
        WHEN @Crs<='–' THEN 'Sun'
        WHEN @Crs<='ÎR' THEN 'Suo'
        WHEN @Crs<='Òk' THEN 'Ta'
        WHEN @Crs<=' M' THEN 'Tai'
        WHEN @Crs<='Ùy' THEN 'Tan'
        WHEN @Crs<=' C' THEN 'Tang'
        WHEN @Crs<='®z' THEN 'Tao'
        WHEN @Crs<='Ïc' THEN 'Te'
        WHEN @Crs<='–Y' THEN 'Teng'
        WHEN @Crs<='ÚŒ' THEN 'Ti'
        WHEN @Crs<='Åq' THEN 'Tian'
        WHEN @Crs<='¼g' THEN 'Tiao'
        WHEN @Crs<='÷Ñ' THEN 'Tie'
        WHEN @Crs<='h' THEN 'Ting'
        WHEN @Crs<='‘q' THEN 'Tong'
        WHEN @Crs<='Í¸' THEN 'Tou'
        WHEN @Crs<='ùr' THEN 'Tu'
        WHEN @Crs<='Ñ‰' THEN 'Tuan'
        WHEN @Crs<='òD' THEN 'Tui'
        WHEN @Crs<='ˆd' THEN 'Tun'
        WHEN @Crs<='»X' THEN 'Tuo'
        WHEN @Crs<='í€' THEN 'Wa'
        WHEN @Crs<='î“' THEN 'Wai'
        WHEN @Crs<='Ú@' THEN 'Wan'
        WHEN @Crs<='–R' THEN 'Wang'
        WHEN @Crs<='Ü^' THEN 'Wei'
        WHEN @Crs<='è·' THEN 'Wen'
        WHEN @Crs<='ýN' THEN 'Weng'
        WHEN @Crs<='ý}' THEN 'Wo'
        WHEN @Crs<='úF' THEN 'Wu'
        WHEN @Crs<='Ða' THEN 'Xi'
        WHEN @Crs<='ç]' THEN 'Xia'
        WHEN @Crs<='ýE' THEN 'Xian'
        WHEN @Crs<='÷P' THEN 'Xiang'
        WHEN @Crs<='”Ã' THEN 'Xiao'
        WHEN @Crs<='õó' THEN 'Xie'
        WHEN @Crs<='á…' THEN 'Xin'
        WHEN @Crs<='ÅB' THEN 'Xing'
        WHEN @Crs<='”¸' THEN 'Xiong'
        WHEN @Crs<='ýM' THEN 'Xiu'
        WHEN @Crs<='Þ£' THEN 'Xu'
        WHEN @Crs<='ÚK' THEN 'Xuan'
        WHEN @Crs<='žy' THEN 'Xue'
        WHEN @Crs<='èR' THEN 'Xun'
        WHEN @Crs<='ý…' THEN 'Ya'
        WHEN @Crs<='ž¹' THEN 'Yan'
        WHEN @Crs<='˜Ó' THEN 'Yang'
        WHEN @Crs<='è€' THEN 'Yao'
        WHEN @Crs<='Œè' THEN 'Ye'
        WHEN @Crs<='ý~' THEN 'Yi'
        WHEN @Crs<='™’' THEN 'Yin'
        WHEN @Crs<='×G' THEN 'Ying'
        WHEN @Crs<='†Ñ' THEN 'Yo'
        WHEN @Crs<='ák' THEN 'Yong'
        WHEN @Crs<='÷ø' THEN 'You'
        WHEN @Crs<=' Œ' THEN 'Yu'
        WHEN @Crs<='îŠ' THEN 'Yuan'
        WHEN @Crs<='ûV' THEN 'Yue'
        WHEN @Crs<='í' THEN 'Yun'
        WHEN @Crs<='ë{' THEN 'Za'
        WHEN @Crs<='¿f' THEN 'Zai'
        WHEN @Crs<='ð•' THEN 'Zan'
        WHEN @Crs<='ÅK' THEN 'Zang'
        WHEN @Crs<='¸^' THEN 'Zao'
        WHEN @Crs<='¶' THEN 'Ze'
        WHEN @Crs<='÷e' THEN 'Zei'
        WHEN @Crs<='‡×' THEN 'Zen'
        WHEN @Crs<='Ù›' THEN 'Zeng'
        WHEN @Crs<='ám' THEN 'Zha'
        WHEN @Crs<='ñ©' THEN 'Zhai'
        WHEN @Crs<='ò–' THEN 'Zhan'
        WHEN @Crs<='²d' THEN 'Zhang'
        WHEN @Crs<='Á^' THEN 'Zhao'
        WHEN @Crs<='úp' THEN 'Zhe'
        WHEN @Crs<='ül' THEN 'Zhen'
        WHEN @Crs<='×C' THEN 'Zheng'
        WHEN @Crs<='ØU' THEN 'Zhi'
        WHEN @Crs<='ÖA' THEN 'Zhong'
        WHEN @Crs<='óE' THEN 'Zhou'
        WHEN @Crs<='èT' THEN 'Zhu'
        WHEN @Crs<='×¦' THEN 'Zhua'
        WHEN @Crs<='ÛJ' THEN 'Zhuai'
        WHEN @Crs<='»M' THEN 'Zhuan'
        WHEN @Crs<='‘Þ' THEN 'Zhuang'
        WHEN @Crs<='èV' THEN 'Zhui'
        WHEN @Crs<='¶›' THEN 'Zhun'
        WHEN @Crs<='»m' THEN 'Zhuo'
        WHEN @Crs<='n' THEN 'Zi'
        WHEN @Crs<='¿v' THEN 'Zong'
        WHEN @Crs<='‹ƒ' THEN 'Zou'
        WHEN @Crs<='ÖŠ' THEN 'Zu'
        WHEN @Crs<='ß¬' THEN 'Zuan'
        WHEN @Crs<='™Þ' THEN 'Zui'
        WHEN @Crs<='ã†' THEN 'Zun'
        WHEN @Crs<='…ø' THEN 'Zuo'
        ELSE  @Crs END);
        SET @StrLen = @StrLen - 1 ;
        
        IF LEN(@tRe) > 0
        BEGIN
			SET @Re = @tRe + ' ' + @Re;

			SET @StrAbbr = SUBSTRING(UPPER(@tRe), 1, 1) + @StrAbbr;
		END
   END
   
   IF @Abbr = 1
   BEGIN
		SET @Re = @Re + '/' + @StrAbbr;
   END
   
   RETURN (@Re);
END
GO


