-- V0.0.8

-- TMS_MEndUser
ALTER TABLE TMS_MEndUser ADD EndUser_CustomerID BIGINT NOT NULL DEFAULT 0;
ALTER TABLE TMS_MEndUser ADD EndUser_CustomerCompanyID BIGINT NULL DEFAULT 0;

-- TMS_MSupplier
ALTER TABLE TMS_MSupplier ALTER COLUMN Supplier_CompanyID BIGINT NULL;

ALTER TABLE TMS_MSupplier ADD Supplier_Name NVARCHAR(300) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Industry INT NULL DEFAULT 0;
ALTER TABLE TMS_MSupplier ADD Supplier_Web NVARCHAR(300) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_ShortName NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_EnName NVARCHAR(200) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_ShortEnName NVARCHAR(50) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Master NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_License NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Contact NVARCHAR(300) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Phone NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Fax NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Mail NVARCHAR(200) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Address NVARCHAR(300) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Zip NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_WeiXin NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Logo NVARCHAR(300) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Bank NVARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_BankAccount VARCHAR(100) NULL;
ALTER TABLE TMS_MSupplier ADD Supplier_Description NVARCHAR(max) NULL;
