-- V0.1.0

-- TMS_OrderIndex
ALTER TABLE TMS_OrderIndex ADD Index_SrcClass BIGINT NOT NULL DEFAULT 0;

-- TMS_MCar
ALTER TABLE TMS_MCar ADD Car_SupplierID BIGINT NOT NULL DEFAULT 0;

-- TMS_MDriver
ALTER TABLE TMS_MDriver ADD Driver_SupplierID BIGINT NOT NULL DEFAULT 0;

-- TMS_OrderIndex
ALTER TABLE TMS_OrderIndex ADD Index_Kms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE TMS_OrderIndex ADD Index_CarType BIGINT NOT NULL DEFAULT 0;
ALTER TABLE TMS_OrderIndex ADD Index_CarLength BIGINT NOT NULL DEFAULT 0;